config/routes.rb
Rails.application.routes.draw do
  get "/" => "homes#top"
  root "books#index"
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new

  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id) #投稿が成功するとそのページへ行く
    else
      @books = Book.all
      render :index # indexの画面へ
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id) 
    else
      @books = Book.all
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= form_with model: @book do |f| %> <!-- 7章にて-->
  <% if @book.errors.any? %>
    <div class="error">error occurred</div>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="form">Title </div>
    <%= f.text_field :title %>

  <div class="form">Body</div>
  <%= f.text_area :body %>

  <br>
  <div class="button">
    <%= f.submit 'Update Book' %>
  </div>

<br>
<%= link_to "Show", @book %> |
<%= link_to "Back", books_path %>

<% end %>

app/views/books/index.html.erb
<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
    </tr>
  </thead>

   <tbody>
     <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to "Show", book_path(book.id) %></td>
        <td><%= link_to "Edit", edit_book_path(book) %></td>
        <td><%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
      </tr>
     <% end %>
   </tbody>
  </table>


  <h2>New book</h2>
  <!-- errorメッセージ -->
  <%= form_with model: @book do |f| %>
  <% if @book.errors.any? %>
    <div class="error">error Occurred</div>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

    <div class="form">Title</div>
    <%= f.text_field :title %>

    <div class="form">Body</div>
    <%= f.text_area :body %>

    <br>
    <div class="button">
      <%= f.submit 'Create Book' %>
    </div>
  <% end %>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div class="success">
  <%= flash[:notice] %>
</div>

<p>
  <b>Title:</b>
  <%= @book.title %>
</p>

<p>
  <b>Body:</b>
  <%= @book.body %>
</p>

<%= link_to "Edit", edit_book_path(@book) %> |
<%= link_to "Back", books_path %>

app/views/homes/top.html.erb
<h1>ようこそ
  <b>Bookers</b>
  へ！
</h1>

<p>
  <b>Bookers</b>
  では、さまざまな書籍に関するあなたの意見や
</p>
<p>印象を共有し交換することができます</p>

<p>
  <a href="/books">start</a>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>